"""Field dictionary and business term mappings for the M6 demo dataset."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class FieldDefinition:
    field_name: str
    business_meaning: str
    data_type: str
    semantic_category: str
    required_for_core_analysis: bool
    common_aliases: tuple[str, ...]
    example_values: tuple[str, ...]
    data_quality_rules: tuple[str, ...]


def _field(
    name: str,
    meaning: str,
    data_type: str,
    category: str,
    required: bool,
    aliases: tuple[str, ...],
    examples: tuple[str, ...],
    rules: tuple[str, ...],
) -> FieldDefinition:
    return FieldDefinition(name, meaning, data_type, category, required, aliases, examples, rules)


FIELD_DICTIONARY: dict[str, FieldDefinition] = {
    "order_id": _field(
        "order_id",
        "唯一合成订单标识，用于订单计数、去重和复购链路。",
        "string",
        "identifier",
        True,
        ("订单ID", "订单号", "订单编号"),
        ("ORD-2026-000001",),
        ("required", "unique", "non_empty"),
    ),
    "order_date": _field(
        "order_date",
        "下单日期，用于趋势、复盘和复购频次分析。",
        "date",
        "time",
        True,
        ("下单日期", "订单日期", "成交日期", "时间"),
        ("2026-06-30",),
        ("required", "parseable_iso_date"),
    ),
    "ship_date": _field(
        "ship_date",
        "发货日期，用于检查履约时效和日期逻辑异常。",
        "date",
        "time",
        False,
        ("发货日期", "出库日期", "配送日期"),
        ("2026-07-03",),
        ("parseable_iso_date", "normally_on_or_after_order_date"),
    ),
    "shipping_days": _field(
        "shipping_days",
        "从下单到发货的天数，代表履约效率。",
        "integer",
        "operational_metric",
        True,
        ("发货周期", "履约时长", "发货天数", "物流时效"),
        ("3", "8"),
        ("integer", "normally_between_0_and_12", "negative_value_is_anomaly"),
    ),
    "region": _field(
        "region",
        "大区市场，用于区域贡献、风险和机会对比。",
        "string",
        "geography",
        True,
        ("地区", "大区", "区域"),
        ("South China", "East China"),
        ("required", "controlled_dimension"),
    ),
    "province": _field(
        "province",
        "省级市场，用于区域下钻。",
        "string",
        "geography",
        False,
        ("省份", "省", "省级市场"),
        ("Guangdong", "Zhejiang"),
        ("non_empty", "consistent_with_region"),
    ),
    "city": _field(
        "city",
        "城市市场，用于城市层级和区域下钻。",
        "string",
        "geography",
        False,
        ("城市", "市", "城市市场"),
        ("Shenzhen", "Hangzhou"),
        ("non_empty", "consistent_with_province"),
    ),
    "city_level": _field(
        "city_level",
        "城市等级，用于一线、新一线、二三四线城市经营差异分析。",
        "string",
        "geography",
        False,
        ("城市等级", "城市线级", "线级"),
        ("Tier 1", "Tier 3"),
        ("controlled_dimension",),
    ),
    "customer_id": _field(
        "customer_id",
        "合成客户标识，允许复购，用于客户贡献和粗略复购分析。",
        "string",
        "customer",
        True,
        ("客户ID", "用户ID", "顾客ID"),
        ("CUST-000123",),
        ("required", "repeatable_identifier"),
    ),
    "customer_segment": _field(
        "customer_segment",
        "客户分层，用于比较高价值、新客、价格敏感等群体表现。",
        "string",
        "customer",
        False,
        ("客户分层", "客户类型", "客群", "用户分层"),
        ("High Value", "Price Sensitive"),
        ("controlled_dimension",),
    ),
    "customer_age": _field(
        "customer_age",
        "合成客户年龄，用于年龄段偏好和风险分析。",
        "integer",
        "customer",
        False,
        ("年龄", "客户年龄", "用户年龄"),
        ("24", "41"),
        ("integer", "between_18_and_65"),
    ),
    "customer_gender": _field(
        "customer_gender",
        "合成客户性别分组，用于基础人群画像。",
        "string",
        "customer",
        False,
        ("性别", "客户性别", "用户性别"),
        ("female", "male", "unknown"),
        ("controlled_dimension",),
    ),
    "ad_channel": _field(
        "ad_channel",
        "获客或订单来源渠道，用于渠道质量、销售贡献和体验风险分析。",
        "string",
        "channel",
        False,
        ("渠道", "广告渠道", "获客渠道", "流量来源"),
        ("Livestream", "Search", "Feed Ads"),
        ("controlled_dimension", "missing_rate_should_be_low"),
    ),
    "category": _field(
        "category",
        "一级商品品类，用于品类贡献、促销依赖和退款风险分析。",
        "string",
        "product",
        True,
        ("品类", "一级品类", "商品大类"),
        ("Digital", "Beauty"),
        ("required", "controlled_dimension"),
    ),
    "subcategory": _field(
        "subcategory",
        "二级商品品类，用于更细的商品结构下钻。",
        "string",
        "product",
        False,
        ("子品类", "二级品类", "小类"),
        ("Smartphones", "Skincare"),
        ("non_empty", "consistent_with_category"),
    ),
    "product": _field(
        "product",
        "商品名称，用于识别高销量低利润商品和退款原因集中商品。",
        "string",
        "product",
        True,
        ("商品", "产品", "SKU", "商品名"),
        ("Promo Jacket", "Hydrating Serum Set"),
        ("required", "controlled_dimension"),
    ),
    "sales_amount": _field(
        "sales_amount",
        "订单销售额，是经营规模、贡献和客单价计算的核心金额。",
        "decimal(2)",
        "financial_metric",
        True,
        ("销售额", "成交额", "GMV", "收入", "销售金额"),
        ("1590.88",),
        ("numeric", "normally_positive", "non_positive_value_is_anomaly"),
    ),
    "quantity": _field(
        "quantity",
        "订单商品数量，用于销量和单价合理性分析。",
        "integer",
        "volume_metric",
        True,
        ("销量", "数量", "件数", "购买数量"),
        ("1", "3"),
        ("integer", "normally_positive", "non_positive_value_is_anomaly"),
    ),
    "unit_price": _field(
        "unit_price",
        "折扣前商品单价，用于价格带和客单价解释。",
        "decimal(2)",
        "financial_metric",
        False,
        ("单价", "商品单价", "原价"),
        ("299.00", "4599.00"),
        ("numeric", "positive"),
    ),
    "discount": _field(
        "discount",
        "折扣率，用于判断促销依赖和利润压力。",
        "decimal(4)",
        "financial_metric",
        True,
        ("折扣", "折扣率", "优惠", "促销力度"),
        ("0.1200", "0.4500"),
        ("numeric", "normally_between_0_and_1", "out_of_range_is_anomaly"),
    ),
    "cost_amount": _field(
        "cost_amount",
        "订单成本金额，用于毛利和利润质量分析。",
        "decimal(2)",
        "financial_metric",
        False,
        ("成本", "成本金额", "商品成本"),
        ("1200.00",),
        ("numeric", "normally_non_negative"),
    ),
    "profit_amount": _field(
        "profit_amount",
        "订单利润金额，用于毛利率、利润贡献和健康增长判断。",
        "decimal(2)",
        "financial_metric",
        True,
        ("利润", "利润额", "毛利", "利润金额"),
        ("220.35", "-12.50"),
        ("numeric", "can_be_negative_after_refund_or_discount"),
    ),
    "refund_amount": _field(
        "refund_amount",
        "退款金额，用于退款率和经营风险判断。",
        "decimal(2)",
        "risk_metric",
        True,
        ("退款金额", "退款", "售后金额"),
        ("0.00", "188.50"),
        ("numeric", "non_negative", "greater_than_sales_is_anomaly"),
    ),
    "is_returned": _field(
        "is_returned",
        "是否发生退货，用于退货率和售后质量分析。",
        "boolean",
        "risk_metric",
        True,
        ("是否退货", "退货标记", "退货"),
        ("true", "false"),
        ("boolean", "consistent_with_return_reason_and_refund"),
    ),
    "return_reason": _field(
        "return_reason",
        "退货原因，用于初步根因分析。",
        "string",
        "risk_reason",
        False,
        ("退货原因", "退款原因", "售后原因"),
        ("Quality Issue", "Slow Logistics"),
        ("controlled_dimension", "none_or_blank_when_not_returned"),
    ),
    "satisfaction_score": _field(
        "satisfaction_score",
        "客户满意度评分，1 到 5 分，用于客户体验判断。",
        "decimal(2)",
        "experience_metric",
        True,
        ("满意度", "满意度评分", "客户评分", "体验评分"),
        ("4.20", "3.10"),
        ("numeric", "between_1_and_5", "missing_rate_allowed_low"),
    ),
    "complaint_count": _field(
        "complaint_count",
        "订单投诉次数，用于客户体验和履约风险判断。",
        "integer",
        "experience_metric",
        True,
        ("投诉", "投诉数", "投诉次数", "客诉"),
        ("0", "2"),
        ("integer", "non_negative"),
    ),
    "payment_method": _field(
        "payment_method",
        "支付方式，用于辅助经营分层，不作为核心健康判断指标。",
        "string",
        "payment",
        False,
        ("支付方式", "付款方式", "支付渠道"),
        ("Alipay", "WeChat Pay"),
        ("controlled_dimension",),
    ),
}


BUSINESS_TERM_MAPPINGS: dict[str, dict[str, tuple[str, ...] | str]] = {
    "销售额": {"fields": ("sales_amount",), "metric": "total_sales"},
    "订单数": {"fields": ("order_id",), "metric": "order_count"},
    "客单价": {"fields": ("sales_amount", "order_id"), "metric": "avg_order_value"},
    "退款金额": {"fields": ("refund_amount",), "metric": "refund_amount"},
    "退款率": {"fields": ("refund_amount", "sales_amount"), "metric": "refund_rate"},
    "退货率": {"fields": ("is_returned", "order_id"), "metric": "return_rate"},
    "毛利率": {"fields": ("profit_amount", "sales_amount"), "metric": "gross_margin_rate"},
    "折扣": {"fields": ("discount",), "metric": "avg_discount"},
    "发货周期": {"fields": ("shipping_days",), "metric": "avg_shipping_days"},
    "满意度": {"fields": ("satisfaction_score",), "metric": "avg_satisfaction_score"},
    "投诉": {"fields": ("complaint_count", "order_id"), "metric": "complaint_rate"},
    "渠道": {"fields": ("ad_channel",), "metric": ""},
    "地区": {"fields": ("region", "province", "city"), "metric": ""},
    "城市等级": {"fields": ("city_level",), "metric": ""},
    "品类": {"fields": ("category", "subcategory"), "metric": ""},
    "商品": {"fields": ("product",), "metric": ""},
    "客户分层": {"fields": ("customer_segment",), "metric": ""},
}


def get_field_definition(field_name: str) -> FieldDefinition | None:
    return FIELD_DICTIONARY.get(field_name)


def map_business_term(term: str) -> dict[str, tuple[str, ...] | str] | None:
    return BUSINESS_TERM_MAPPINGS.get(term.strip())
