"""Normalize and validate SQL generated by LLMs."""

from __future__ import annotations

import re

from backend.services.sql_validator import validate_readonly


_CANNOT_ANSWER_RE = re.compile(r"--\s*CANNOT_ANSWER\s*:?.*", re.IGNORECASE | re.DOTALL)
_FENCE_RE = re.compile(r"```(?:sql|duckdb|SQL|DuckDB)?\s*(.*?)```", re.DOTALL)
_SQL_START_RE = re.compile(
    r"\b(SELECT|WITH|EXPLAIN|DESCRIBE|DESC|SHOW|TABLE|VALUES|FROM)\b",
    re.IGNORECASE,
)
_LABEL_RE = re.compile(r"^(SQL|QUERY)\s*:\s*", re.IGNORECASE)


def extract_sql_from_llm_output(raw: str) -> str:
    """Extract a runnable read-only SQL candidate from raw LLM output.

    The model is instructed to return SQL only, but production calls can still
    contain prose, markdown fences, or provider-specific non-text artifacts.
    """
    text = (raw or "").strip()
    if not text:
        return "-- CANNOT_ANSWER: Model returned an empty SQL response."

    cannot_answer = _CANNOT_ANSWER_RE.search(text)
    if cannot_answer:
        return _normalize_cannot_answer(cannot_answer.group(0))

    fenced = _extract_from_fence(text)
    if fenced:
        return fenced

    start = _SQL_START_RE.search(text)
    if start:
        return _trim_to_first_statement(text[start.start():])

    return "-- CANNOT_ANSWER: Model returned non-SQL text."


def validate_generated_sql(sql: str) -> tuple[bool, str]:
    """Validate generated SQL while allowing explicit cannot-answer comments."""
    normalized = sql.strip()
    if normalized.upper().startswith("-- CANNOT_ANSWER"):
        return True, ""
    return validate_readonly(normalized)


def build_sql_quality_gates(sql: str, validation_error: str = "") -> list[dict]:
    """Build compact quality gates for generated SQL responses."""
    normalized = sql.strip()
    has_sql_or_decision = bool(normalized)
    readonly_passed = not validation_error
    return [
        {
            "name": "sql_or_cannot_answer",
            "passed": has_sql_or_decision,
            "message": "" if has_sql_or_decision else "No SQL or cannot-answer decision was produced.",
        },
        {
            "name": "readonly_sql",
            "passed": readonly_passed,
            "message": validation_error,
        },
    ]


def _extract_from_fence(text: str) -> str:
    for match in _FENCE_RE.finditer(text):
        candidate = _trim_to_first_statement(match.group(1))
        if candidate.upper().startswith("-- CANNOT_ANSWER") or _SQL_START_RE.search(candidate):
            return candidate
    return ""


def _trim_to_first_statement(candidate: str) -> str:
    """Extract only the first SQL statement from candidate text.

    Stops at the first semicolon. If no semicolon found, attempts to
    detect where SQL ends and prose begins (e.g. Chinese explanation text).
    """
    cleaned = _LABEL_RE.sub("", candidate.strip())
    semicolon = cleaned.find(";")
    if semicolon >= 0:
        cleaned = cleaned[: semicolon + 1]
        return cleaned.strip()

    # No semicolon — try to detect SQL/prose boundary
    # Split by lines and keep only lines that look like SQL
    lines = cleaned.split("\n")
    sql_lines = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            # Empty line — might be between SQL and prose, stop here
            if sql_lines:
                break
            continue
        # If line starts with non-ASCII and doesn't look like SQL, stop
        if _is_prose_line(stripped):
            break
        sql_lines.append(stripped)
    return "\n".join(sql_lines).strip()


def _is_prose_line(line: str) -> bool:
    """Detect if a line is prose (explanation/mapping text) rather than SQL."""
    import unicodedata
    if not line:
        return False
    # Lines starting with common prose markers
    prose_prefixes = ("映射", "说明", "解释", "注意", "备注", "mapping", "note:", "explanation:")
    lower = line.lower()
    for prefix in prose_prefixes:
        if lower.startswith(prefix):
            return True
    # Lines that are mostly non-ASCII (Chinese explanation) and don't contain SQL keywords
    first_char = line[0]
    if ord(first_char) > 127:
        # Check if line contains any SQL keywords
        upper = line.upper()
        sql_keywords = ("SELECT", "FROM", "WHERE", "GROUP", "ORDER", "JOIN", "ON", "AS", "AND", "OR")
        if not any(kw in upper for kw in sql_keywords):
            return True
    return False


def _normalize_cannot_answer(candidate: str) -> str:
    cleaned = candidate.strip()
    if ":" not in cleaned:
        return "-- CANNOT_ANSWER: The available data cannot answer this question."
    reason = cleaned.split(":", 1)[1].strip()
    return f"-- CANNOT_ANSWER: {reason or 'The available data cannot answer this question.'}"
