import { fireEvent, render, screen } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AstryxDataAgentWorkbench, BusinessResult } from "@/components/astryx/astryx-data-agent-workbench";
import type { BusinessAnalysisRecord } from "@/stores/astryx-workbench-store";
import type { AgentBusinessReport } from "@/services/api";
import { downloadBlob } from "@/utils/download";

vi.mock("react-i18next", () => ({
  useTranslation: () => ({
    i18n: {
      language: "en",
      changeLanguage: vi.fn(),
    },
    t: (key: string) => {
      const labels: Record<string, string> = {
        "astryx.result.title": "Business answer",
        "astryx.result.executive-summary": "Executive summary",
        "astryx.result.key-findings": "Key findings",
        "astryx.result.evidence-summary": "Evidence summary",
        "astryx.result.risk-priorities": "Risk priorities",
        "astryx.result.opportunities": "Growth opportunities",
        "astryx.result.recommendations": "Recommendations",
        "astryx.result.priority-actions": "Priority actions",
        "astryx.result.recommendation-why": "Why",
        "astryx.result.recommendation-how": "How",
        "astryx.result.recommendation-metrics": "Metrics to watch",
        "astryx.result.recommendation-deadline": "Timeline",
        "astryx.result.recommendation-owner": "Suggested owner",
        "astryx.result.limitations": "Limitations",
        "astryx.result.next-questions": "Next questions",
        "astryx.result.risk-high": "High risk",
        "astryx.result.risk-medium": "Medium risk",
        "astryx.result.risk-low": "Low risk",
        "astryx.result.risk-other": "Other risks",
        "astryx.result.answer": "Analysis conclusion",
        "astryx.result.findings": "Key findings",
        "astryx.result.next": "Next questions",
        "astryx.result.data": "Data evidence",
        "astryx.result.no-data": "No data",
        "astryx.result.warnings": "Risk notes",
        "astryx.result.sql": "View SQL",
        "astryx.result.no-sql": "No SQL",
        "astryx.result.technical": "Technical details / Data evidence",
        "astryx.result.provider-requested": "Requested model",
        "astryx.result.provider-used": "Model used",
        "astryx.result.provider-status": "Provider status",
        "astryx.result.fallback-reason": "Fallback reason",
        "astryx.result.record": "Record",
        "astryx.result.none": "None",
        "astryx.status.completed": "Completed",
        "astryx.status.demo": "Demo fallback",
        "astryx.provider.mock-title": "Demo mode",
        "astryx.provider.mock-desc": "This result is generated by the mock analysis path.",
        "astryx.provider.fallback-title": "Simulated result after provider fallback",
        "astryx.provider.fallback-desc": "The requested model service timed out or was unavailable.",
        "astryx.provider.error-title": "Model analysis failed",
        "astryx.provider.error-desc": "The requested model failed and no fallback result is available.",
        "astryx.provider.reason": "Reason",
        "astryx.export.markdown": "Export Markdown",
        "astryx.export.html": "Export HTML",
        "astryx.export.disabled": "No report available to export",
      };
      return labels[key] ?? key;
    },
  }),
}));

vi.mock("@/panels/sql-workspace-panel", () => ({
  SqlWorkspacePanel: () => <div data-testid="sql-workspace-panel" />,
}));

vi.mock("@/utils/download", () => ({
  downloadBlob: vi.fn(),
}));

const businessReport: AgentBusinessReport = {
  executive_summary: "Overall revenue is strong, but refund and service risks need priority attention.",
  key_findings: ["South China is high revenue and high risk.", "East China is stable with healthier margin."],
  evidence_summary: [
    { summary: "Total sales reached 12.5M.", metric: "total_sales" },
    { summary: "Refund rate is above the default risk threshold.", metric: "refund_rate" },
  ],
  risk_priorities: [
    { risk_name: "South China refund pressure", risk_level: "high", reason: "High sales and high refund rate." },
    { risk_name: "Promotion dependency", risk_level: "medium", reason: "High discount with low margin." },
  ],
  recommendations: [
    {
      priority: "high",
      action: "Audit the top refund products in South China this week.",
      why: "South China has strong sales but weaker refund and complaint indicators.",
      how: "Group recent refund orders by category, product, and return reason.",
      metrics: ["Refund rate", "Complaint rate", "Satisfaction", "Top return reasons"],
      deadline: "Finish the first review within 1 week",
      owner_hint: "Operations / After-sales / Product owner",
      reason: "Legacy reason should not be the primary text.",
      monitoring_metric: "legacy_refund_rate",
      expected_action_window: "legacy window",
    },
  ],
  limitations: ["ROI cannot be calculated without ad_spend or campaign_cost."],
  next_questions: ["Continue by product category in high-risk regions."],
};

function makeRecord(report: AgentBusinessReport | null = businessReport): BusinessAnalysisRecord {
  return {
    runId: "run-business-1",
    question: "Assess business health.",
    tableName: "demo_sales_business_50k",
    answer: "Legacy answer should not be the primary report when business_report exists.",
    businessReport: report,
    businessReportViewModel: null,
    findings: ["Legacy finding"],
    evidencePreview: [],
    sql: "SELECT * FROM revenue",
    warnings: [],
    nextSteps: ["Legacy next question"],
    requestedProvider: "doubao",
    providerRequested: "doubao",
    providerUsed: "doubao",
    providerStatus: "live_success",
    isSimulated: false,
    fallbackTriggered: false,
    fallbackReason: null,
    status: "completed",
    createdAt: "2026-07-07T00:00:00.000Z",
    rawRun: {
      run_id: "run-business-1",
      status: "completed",
      answer: "Legacy answer should not be the primary report when business_report exists.",
      business_report: report,
      sql: "SELECT * FROM revenue",
      requested_provider: "doubao",
      provider_requested: "doubao",
      provider_used: "doubao",
      provider_status: "live_success",
      is_simulated: false,
      fallback_reason: null,
      memory_used: true,
      trace: { step: "hidden trace" },
      tool_calls: [{ tool_name: "compute_overall_kpis" }],
    },
  };
}

describe("M6.6 Business Report frontend adaptation", () => {
  beforeEach(() => {
    vi.mocked(downloadBlob).mockClear();
  });

  it("renders business_report as the default user-facing report with recommendations before evidence", () => {
    render(<BusinessResult record={makeRecord()} rows={[]} columns={[]} />);

    expect(screen.getByText("Overall revenue is strong, but refund and service risks need priority attention.")).toBeInTheDocument();
    expect(screen.getByText("South China is high revenue and high risk.")).toBeInTheDocument();
    expect(screen.getByText("Total sales reached 12.5M.")).toBeInTheDocument();
    expect(screen.getByText("South China refund pressure")).toBeInTheDocument();
    expect(screen.getByText("Audit the top refund products in South China this week.")).toBeInTheDocument();
    expect(screen.getByText("South China has strong sales but weaker refund and complaint indicators.")).toBeInTheDocument();
    expect(screen.getByText("Group recent refund orders by category, product, and return reason.")).toBeInTheDocument();
    expect(screen.getByText("Finish the first review within 1 week")).toBeInTheDocument();
    expect(screen.getByText("Operations / After-sales / Product owner")).toBeInTheDocument();
    expect(screen.getByText("Refund rate")).toBeInTheDocument();
    expect(screen.getByText("ROI cannot be calculated without ad_spend or campaign_cost.")).toBeInTheDocument();
    expect(screen.getByText("Continue by product category in high-risk regions.")).toBeInTheDocument();

    const content = document.body.textContent ?? "";
    expect(content.indexOf("Priority actions")).toBeGreaterThan(-1);
    expect(content.indexOf("Evidence summary")).toBeGreaterThan(-1);
    expect(content.indexOf("Priority actions")).toBeLessThan(content.indexOf("Evidence summary"));
    expect(content).not.toContain("legacy_refund_rate");
  });

  it("keeps SQL, trace, tool calls, provider, run id and memory hidden by default", () => {
    render(<BusinessResult record={makeRecord()} rows={[]} columns={[]} />);

    expect(screen.queryByText("SELECT * FROM revenue")).not.toBeInTheDocument();
    expect(screen.queryByText("hidden trace")).not.toBeInTheDocument();
    expect(screen.queryByText("compute_overall_kpis")).not.toBeInTheDocument();
    expect(screen.queryByText("doubao")).not.toBeInTheDocument();
    expect(screen.queryByText("run-business-1")).not.toBeInTheDocument();
    expect(screen.queryByText("memory_used")).not.toBeInTheDocument();
    expect(screen.queryByText("Data evidence")).not.toBeInTheDocument();
  });

  it("exports the business report as fixed-template Markdown without raw technical details", () => {
    render(<BusinessResult record={makeRecord()} rows={[]} columns={[]} />);

    fireEvent.click(screen.getByRole("button", { name: /Export Markdown/ }));

    expect(downloadBlob).toHaveBeenCalledTimes(1);
    const [filename, content, mimeType] = vi.mocked(downloadBlob).mock.calls[0];
    expect(filename).toMatch(/^business-report-\d{8}-\d{6}\.md$/);
    expect(mimeType).toBe("text/markdown;charset=utf-8");
    expect(String(content)).toContain("# Business Diagnosis Report");
    expect(String(content)).toContain("## 3. Top 3 priority action suggestions");
    expect(String(content)).toContain("Audit the top refund products in South China this week.");
    expect(String(content)).not.toContain("SELECT * FROM revenue");
    expect(String(content)).not.toContain("compute_overall_kpis");
    expect(String(content)).not.toContain("hidden trace");
    expect(String(content)).not.toContain("rawRun");
  });

  it("exports a lightweight HTML report with the same fixed structure", () => {
    render(<BusinessResult record={makeRecord()} rows={[]} columns={[]} />);

    fireEvent.click(screen.getByRole("button", { name: /Export HTML/ }));

    expect(downloadBlob).toHaveBeenCalledTimes(1);
    const [filename, content, mimeType] = vi.mocked(downloadBlob).mock.calls[0];
    expect(filename).toMatch(/^business-report-\d{8}-\d{6}\.html$/);
    expect(mimeType).toBe("text/html;charset=utf-8");
    expect(String(content)).toContain("<!doctype html>");
    expect(String(content)).toContain("Business Diagnosis Report");
    expect(String(content)).not.toContain("SELECT * FROM revenue");
  });

  it("disables report export when business_report is missing", () => {
    render(<BusinessResult record={makeRecord(null)} rows={[]} columns={[]} />);

    expect(screen.getByRole("button", { name: /Export Markdown/ })).toBeDisabled();
    expect(screen.getByRole("button", { name: /Export HTML/ })).toBeDisabled();
  });

  it("does not show a fallback banner when provider_status is live_success", () => {
    render(<BusinessResult record={makeRecord()} rows={[]} columns={[]} />);

    expect(screen.queryByText("Simulated result after provider fallback")).not.toBeInTheDocument();
    expect(screen.queryByText("Demo mode")).not.toBeInTheDocument();
    expect(screen.queryByText("Model analysis failed")).not.toBeInTheDocument();
  });

  it("shows demo mode when provider_status is mock", () => {
    render(
      <BusinessResult
        record={{
          ...makeRecord(),
          requestedProvider: "mock",
          providerRequested: "mock",
          providerUsed: "mock",
          providerStatus: "mock",
          isSimulated: true,
        }}
        rows={[]}
        columns={[]}
      />
    );

    expect(screen.getByText("Demo mode")).toBeInTheDocument();
    expect(screen.getByText("This result is generated by the mock analysis path.")).toBeInTheDocument();
  });

  it("shows a fallback banner when provider_status is fallback", () => {
    render(
      <BusinessResult
        record={{
          ...makeRecord(),
          providerUsed: "mock",
          providerStatus: "fallback",
          isSimulated: true,
          fallbackTriggered: true,
          fallbackReason: "provider_request_failed",
        }}
        rows={[]}
        columns={[]}
      />
    );

    expect(screen.getByText("Simulated result after provider fallback")).toBeInTheDocument();
    expect(screen.getByText("The requested model service timed out or was unavailable.")).toBeInTheDocument();
    expect(screen.getByText(/provider_request_failed/)).toBeInTheDocument();
  });

  it("shows an explicit error state instead of a successful report banner", () => {
    render(
      <BusinessResult
        record={{
          ...makeRecord(),
          status: "failed",
          providerStatus: "error",
          isSimulated: false,
          fallbackTriggered: false,
          fallbackReason: "provider_request_failed",
        }}
        rows={[]}
        columns={[]}
      />
    );

    expect(screen.getByText("Model analysis failed")).toBeInTheDocument();
    expect(screen.getByText("The requested model failed and no fallback result is available.")).toBeInTheDocument();
    expect(screen.queryByTestId("business-report-view")).not.toBeInTheDocument();
  });

  it("uses provider_status before legacy provider_used and fallback fields", () => {
    render(
      <BusinessResult
        record={{
          ...makeRecord(),
          providerUsed: "mock",
          providerStatus: "live_success",
          isSimulated: false,
          fallbackTriggered: true,
          fallbackReason: "legacy fallback flag should not win",
        }}
        rows={[]}
        columns={[]}
      />
    );

    expect(screen.queryByText("Simulated result after provider fallback")).not.toBeInTheDocument();
  });

  it("falls back to is_simulated when provider_status is absent", () => {
    render(
      <BusinessResult
        record={{
          ...makeRecord(),
          providerStatus: null,
          providerUsed: "mock",
          isSimulated: true,
        }}
        rows={[]}
        columns={[]}
      />
    );

    expect(screen.getByText("Demo mode")).toBeInTheDocument();
  });

  it("shows technical details only after the accordion is expanded", () => {
    render(<BusinessResult record={makeRecord()} rows={[{ order_id: "o-1", sales_amount: 100 }]} columns={["order_id", "sales_amount"]} />);

    fireEvent.click(screen.getByRole("button", { name: "Technical details / Data evidence" }));

    expect(screen.getByText("SELECT * FROM revenue")).toBeInTheDocument();
    expect(screen.getByText(/compute_overall_kpis/)).toBeInTheDocument();
    expect(screen.getByText(/hidden trace/)).toBeInTheDocument();
    expect(screen.getAllByText("doubao").length).toBeGreaterThan(0);
    expect(screen.getAllByText("run-business-1").length).toBeGreaterThan(0);
    expect(screen.getByText(/memory_used/)).toBeInTheDocument();
    expect(screen.getByText("Data evidence")).toBeInTheDocument();
    expect(screen.getByText("order_id")).toBeInTheDocument();
  });

  it("fills the full next question through the chip callback without submitting", () => {
    const onNextQuestionSelect = vi.fn();
    render(
      <BusinessResult
        record={makeRecord({
          ...businessReport,
          next_questions: ["Continue by product category in high-risk regions with a very detailed follow-up question."],
        })}
        rows={[]}
        columns={[]}
        onNextQuestionSelect={onNextQuestionSelect}
      />
    );

    fireEvent.click(screen.getByRole("button", { name: /Continue by product category/ }));

    expect(onNextQuestionSelect).toHaveBeenCalledWith("Continue by product category in high-risk regions with a very detailed follow-up question.");
    expect(onNextQuestionSelect).toHaveBeenCalledTimes(1);
  });

  it("does not invoke next question callback while submission is running", () => {
    const onNextQuestionSelect = vi.fn();
    render(
      <BusinessResult
        record={makeRecord()}
        rows={[]}
        columns={[]}
        onNextQuestionSelect={onNextQuestionSelect}
        nextQuestionDisabled
      />
    );

    fireEvent.click(screen.getByRole("button", { name: "Continue by product category in high-risk regions." }));

    expect(onNextQuestionSelect).not.toHaveBeenCalled();
  });

  it("uses legacy recommendation fields only when new fields are missing", () => {
    const legacyReport: AgentBusinessReport = {
      ...businessReport,
      recommendations: [
        {
          action: "Review legacy promotion risk.",
          reason: "Legacy reason is available.",
          monitoring_metric: "legacy_margin",
          expected_action_window: "legacy 7 days",
        },
      ],
    };

    render(<BusinessResult record={makeRecord(legacyReport)} rows={[]} columns={[]} />);

    expect(screen.getByText("Review legacy promotion risk.")).toBeInTheDocument();
    expect(screen.getByText("Legacy reason is available.")).toBeInTheDocument();
    expect(screen.getByText("legacy_margin")).toBeInTheDocument();
    expect(screen.getByText("legacy 7 days")).toBeInTheDocument();
  });

  it("falls back to the legacy answer when business_report is missing", () => {
    render(<BusinessResult record={makeRecord(null)} rows={[]} columns={[]} />);

    expect(screen.getByText("Legacy answer should not be the primary report when business_report exists.")).toBeInTheDocument();
    expect(screen.getByText("Legacy finding")).toBeInTheDocument();
  });

  it("does not crash or render empty headings for an empty business_report", () => {
    render(<BusinessResult record={makeRecord({})} rows={[]} columns={[]} />);

    expect(screen.queryByTestId("business-report-view")).not.toBeInTheDocument();
    expect(screen.getByText("Legacy answer should not be the primary report when business_report exists.")).toBeInTheDocument();
  });

  it("keeps the single-page Astryx workbench shell without Sidebar or five-tab navigation regression", () => {
    const { container } = render(<AstryxDataAgentWorkbench />);

    expect(container.querySelector("[data-astryx-workbench]")).toBeInTheDocument();
    expect(container.textContent).not.toContain("Sidebar");
    expect(container.textContent).not.toContain("Templates");
    expect(container.textContent).not.toContain("Schedule");
    expect(container.textContent).not.toContain("Diff");
    expect(container.textContent).not.toContain("Timeline");
  });
});
